# Generated by Django 3.1.3 on 2021-05-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mood',
            field=models.TextField(choices=[('B', 'Bad'), ('H', 'Happy'), ('S', 'Soso')], default='S', help_text='Select your mood'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
